apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
  volumeMode: Filesystem
