apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-summarizer-config
data:
  PROMPT_TEMPLATE: |
    Summarize this conversation taken from Slack, by describing the core problem that's being discussed
    and the currect action plan in a concise manner; be specific about what software components, repositories
    or Jira tickets are involved; report the most relevant links; only include the final summary in your response;
    use a narrative form; do not use a conversational form. Here is the conversation:


    {{ text }}
